services:
  api-gtw:
    build: .
    ports:
      - "8000:8000" # HTTP Service port
      - "8443:8443" # HTTPS Service port
      - "8001:8001" # HTTP Admin port
      - "8444:8444" # HTTPS Admin port
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"
    networks:
      - kong-net

networks:
  kong-net:
    external: false
