services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    ports:
      - "5672:5672"     # AMQP Protocol
      - "15672:15672"   # Admin Port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    env_file:
      - .env
